enabledServers:
  - lobby
  - 1.20
  - exhibition
  - 1.12
  - project
aliasservers:
  business:
    bu118: '商单服'
    bu119: '商单服'
    # 其他服务器别名配置
  project:
    project: '项目服'
  community:
    '1.20': '社区服'
  comprehensive:
    '1.12': '综合服'
  exhibition:
    exhibition: '展览馆'
  games:
    nmbs: '小游戏服'
    hungergames: '小游戏服'
    bingo: '小游戏服'
    blockhunt: '小游戏服'
    bedwars: '小游戏服'
    bridge: '小游戏服'